"use client";

import { useState } from "react";

type QueryResponse = {
  success?: boolean;

  farm?: {
    id: string;
    name: string;
  };

  query?: unknown;

  /*
   * Trusted deterministic result produced
   * by the farm intelligence engine.
   */
  deterministicResult?: {
    success?: boolean;
    answer?: string;
    value?: unknown;
    data?: unknown;
    [key: string]: unknown;
  };

  /*
   * Natural-language answer generated by Gemini.
   */
  answer?: string;

  error?: string;
};


const suggestedQuestions = [
  "How much milk did Bahati produce?",
  "How much did we spend on feed?",
  "How many cows are pregnant?",
  "What is my net income?",
  "How many health events have been recorded?",
];


export default function IntelligenceChat() {

  const [question, setQuestion] =
    useState("");

  const [response, setResponse] =
    useState<QueryResponse | null>(null);

  const [loading, setLoading] =
    useState(false);

  const [error, setError] =
    useState("");


  /*
   * =========================================================
   * ASK QUESTION
   * =========================================================
   */

  async function askQuestion(
    questionText?: string
  ) {

    const finalQuestion =
      (
        questionText ??
        question
      ).trim();


    if (
      !finalQuestion ||
      loading
    ) {
      return;
    }


    setLoading(true);

    setError("");

    setResponse(null);


    try {

      const res =
        await fetch(
          "/api/intelligence/query",
          {
            method: "POST",

            headers: {
              "Content-Type":
                "application/json",
            },

            body:
              JSON.stringify({
                question:
                  finalQuestion,
              }),
          }
        );


      const result =
        (await res.json()) as QueryResponse;


      if (!res.ok) {

        throw new Error(
          result.error ||
            "Unable to process your question."
        );

      }


      setResponse(result);

    } catch (err) {

      console.error(
        "Intelligence query error:",
        err
      );


      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong while processing your question."
      );

    } finally {

      setLoading(false);

    }

  }


  /*
   * =========================================================
   * FORM SUBMISSION
   * =========================================================
   */

  function handleSubmit(
    event: React.FormEvent<HTMLFormElement>
  ) {

    event.preventDefault();

    void askQuestion();

  }


  return (

    <div className="space-y-6">


      {/* =====================================================
          QUESTION INPUT
      ===================================================== */}

      <form
        onSubmit={handleSubmit}
        className="space-y-3"
      >

        <div className="flex flex-col gap-3 sm:flex-row">

          <input
            type="text"
            value={question}
            onChange={(event) =>
              setQuestion(
                event.target.value
              )
            }
            placeholder="Ask something about your farm..."
            disabled={loading}
            className="
              min-h-12
              flex-1
              rounded-xl
              border
              border-gray-300
              bg-white
              px-4
              text-sm
              text-gray-900
              outline-none
              placeholder:text-gray-400
              focus:border-green-600
              focus:ring-2
              focus:ring-green-100
              disabled:bg-gray-100
            "
          />


          <button
            type="submit"
            disabled={
              loading ||
              !question.trim()
            }
            className="
              min-h-12
              rounded-xl
              bg-green-700
              px-6
              text-sm
              font-semibold
              text-white
              transition
              hover:bg-green-800
              disabled:cursor-not-allowed
              disabled:bg-gray-300
            "
          >

            {loading
              ? "Thinking..."
              : "Ask"}

          </button>

        </div>

      </form>


      {/* =====================================================
          SUGGESTED QUESTIONS
      ===================================================== */}

      <div>

        <p className="mb-3 text-sm font-medium text-gray-700">
          Try asking:
        </p>


        <div className="flex flex-wrap gap-2">

          {suggestedQuestions.map(
            (suggestion) => (

              <button
                key={suggestion}
                type="button"
                disabled={loading}
                onClick={() => {

                  setQuestion(
                    suggestion
                  );

                  void askQuestion(
                    suggestion
                  );

                }}
                className="
                  rounded-full
                  border
                  border-gray-200
                  bg-gray-50
                  px-3
                  py-2
                  text-left
                  text-xs
                  text-gray-700
                  transition
                  hover:border-green-300
                  hover:bg-green-50
                  hover:text-green-800
                  disabled:cursor-not-allowed
                  disabled:opacity-50
                "
              >

                {suggestion}

              </button>

            )
          )}

        </div>

      </div>


      {/* =====================================================
          LOADING
      ===================================================== */}

      {loading && (

        <div className="
          rounded-2xl
          border
          border-green-100
          bg-green-50
          p-5
        ">

          <div className="flex items-center gap-3">

            <div className="
              h-5
              w-5
              animate-spin
              rounded-full
              border-2
              border-green-200
              border-t-green-700
            " />


            <div>

              <p className="
                font-semibold
                text-green-900
              ">
                Ensinyo Intelligence is thinking...
              </p>


              <p className="
                mt-1
                text-sm
                text-green-700
              ">
                Checking your farm data.
              </p>

            </div>

          </div>

        </div>

      )}


      {/* =====================================================
          ERROR
      ===================================================== */}

      {error && (

        <div className="
          rounded-2xl
          border
          border-red-200
          bg-red-50
          p-5
        ">

          <p className="
            font-semibold
            text-red-800
          ">
            Unable to answer
          </p>


          <p className="
            mt-1
            text-sm
            leading-6
            text-red-700
          ">
            {error}
          </p>

        </div>

      )}


      {/* =====================================================
          INTELLIGENCE RESPONSE
      ===================================================== */}

      {response && !error && (

        <section className="
          overflow-hidden
          rounded-2xl
          border
          border-gray-200
          bg-white
          shadow-sm
        ">


          {/* =================================================
              RESPONSE HEADER
          ================================================= */}

          <div className="
            border-b
            border-gray-200
            bg-gray-50
            px-6
            py-4
          ">

            <div className="
              flex
              items-center
              gap-3
            ">

              <div className="
                flex
                h-10
                w-10
                items-center
                justify-center
                rounded-xl
                bg-green-100
                text-xl
              ">
                🧠
              </div>


              <div>

                <p className="
                  text-sm
                  font-semibold
                  text-gray-900
                ">
                  Intelligence Response
                </p>


                <p className="
                  text-xs
                  text-gray-500
                ">
                  Based on your farm data
                </p>

              </div>

            </div>

          </div>


          {/* =================================================
              RESPONSE BODY
          ================================================= */}

          <div className="
            bg-white
            px-6
            py-6
          ">

            <p className="
              mb-2
              text-xs
              font-semibold
              uppercase
              tracking-wide
              text-green-700
            ">
              Answered
            </p>


            <div className="
              text-base
              leading-7
              text-gray-900
            ">

              {response.answer ? (

                <p className="
                  whitespace-pre-wrap
                  text-gray-900
                ">
                  {response.answer}
                </p>

              ) : (

                <p className="
                  text-gray-600
                ">
                  The intelligence engine returned
                  a result, but no answer was generated.
                </p>

              )}

            </div>

          </div>

        </section>

      )}

    </div>

  );

}